<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="preyas-r" failures="1" tests="4" name="Runners.TestRunner" time="5.651" errors="0" timestamp="2022-07-01T12:38:34 IST" skipped="0">
  <testcase classname="Runners.TestRunner" name="runScenario" time="3.293"/>
  <system-out/>
  <testcase classname="Runners.TestRunner" name="runScenario" time="0.777">
    <failure message="expected [401] but found [201]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [401] but found [201]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at StepDefinations.sample.user_are_verify_invalid_status_code_is(sample.java:597)
at âœ½.user are verify invalid status code is "401"(file:///home/preyas.r@ah.zymrinc.com/Desktop/preyas/Eclipse-NEw-Workspace/API_FrameworkTesting/src/test/java/Feature/BasicAuth_Bearer.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="Runners.TestRunner" name="runScenario" time="0.740"/>
  <system-out/>
  <testcase classname="Runners.TestRunner" name="runScenario" time="0.841"/>
  <system-out/>
</testsuite> <!-- Runners.TestRunner -->
